backend:
  name: github
  repo: raphaelgabbay/Raphael-Gabbay-Website  # Remplace avec ton nom d'utilisateur GitHub et le nom de ton dépôt

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
